language: java
jdk:
- oraclejdk7
deploy:
- provider: s3
  access_key_id: AKIAJNWK6XDCHQMPPTAQ
  secret_access_key: &1
    secure: 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
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: ioanamartin/csyilab5
  bucket: bucketlab5
  region: eu-west-1
- provider: codedeploy
  bucket: bucketlab5
  access_key_id: AKIAJNWK6XDCHQMPPTAQ
  secret_access_key: *1
  key: csyi-lab-5.tgz
  bundle_type: tgz
  application: csyilab5
  deployment_group: DemoFleet
  on: *2
  region: eu-west-1
before_deploy:
- mkdir -p dpl_cd_upload
- cp -r codedeploy target
- cp target/cloudshape-1.0.0.jar target/codedeploy
- tar -czvf dpl_cd_upload/csyi-lab-5.tgz -C target/codedeploy .
- mv dpl_cd_upload/csyi-lab-5.tgz target/codedeploy
